# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feat/*
  paths:
    include:
      - 'service-b/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello from 'service-b'"

- script: npm install
  workingDirectory: b/

- script: npm run chalk
  workingDirectory: b/